matrix:
  include:
    - os: linux
      language: android
      components:
          - build-tools-28.0.0
          - android-28
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-28
      licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      before_install:
          - echo y | sudo apt-get update
          - echo y | sudo apt-get install ruby-dev
          - echo y | sudo apt-get install gcc
          - echo y | sudo apt-get install build-essential
          - echo y | android update sdk -u -a -t build-tools-28.0.0
          - yes | sdkmanager "platforms;android-28"
          - gem install fastlane
          - sudo apt-get autoremove
      env:
          - BRANCH_NAME=$TRAVIS_BRANCH
          - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
      script:
          - ./gradlew build
